###
# Ингридиенты
###
GET http://127.0.0.1:8000/api/ingredients/3/

###
# Пользователи
###
GET http://127.0.0.1:8000/api/users/
###
GET http://127.0.0.1:8000/api/users/
Authorization: Token 286de687a34610db7b67ce7113d25357e94493cd
###
GET http://127.0.0.1:8000/api/users/?limit=2
###
GET http://127.0.0.1:8000/api/users/3/
###
GET http://127.0.0.1:8000/api/users/3/
Authorization: Token 286de687a34610db7b67ce7113d25357e94493cd
###
POST http://127.0.0.1:8000/api/auth/token/login/
Content-Type: application/json

{
    "password": "0123456789",
    "email": "admin@admin.ru"
}
###
POST http://127.0.0.1:8000/api/auth/token/login/
Content-Type: application/json

{
    "password": "Qwerty123",
    "email": "vpupkin9@yandex.ru"
}
###
GET http://127.0.0.1:8000/api/users/me/
###
GET http://127.0.0.1:8000/api/users/me/
Authorization: Token 286de687a34610db7b67ce7113d25357e94493cd
###
POST http://127.0.0.1:8000/api/users/
Content-Type: application/json

{
    "email": "vpupkin9@yandex.ru",
    "username": "vasya.pupkin9",
    "first_name": "Вася9",
    "last_name": "Пупкин9",
    "password": "Qwerty123"
}
###
POST http://127.0.0.1:8000/api/users/set_password/
Content-Type: application/json
Authorization: Token 286de687a34610db7b67ce7113d25357e94493cd

{
    "new_password": "0123456789",
    "current_password": "987654321"
}
###
POST http://127.0.0.1:8000/api/users/set_password/
Content-Type: application/json
Authorization: Token 286de687a34610db7b67ce7113d25357e94493cd

{
    "new_password": "987654321"
}
###
POST http://127.0.0.1:8000/api/users/set_password/
Content-Type: application/json

{
    "new_password": "987654321",
    "current_password": "0123456789"
}
###
POST http://127.0.0.1:8000/api/auth/token/logout/
Content-Type: application/json
Authorization: Token 286de687a34610db7b67ce7113d25357e94493cd