###
# Пользователи
###
GET http://127.0.0.1:8000/api/users/
###
GET http://127.0.0.1:8000/api/users/
Authorization: Token 7018a6e6ce04ae3542c95abd631e0583ff3b9f6a
###
GET http://127.0.0.1:8000/api/users/?limit=2
###
GET http://127.0.0.1:8000/api/users/3/
###
GET http://127.0.0.1:8000/api/users/3/
Authorization: Token 7018a6e6ce04ae3542c95abd631e0583ff3b9f6a
###
POST http://127.0.0.1:8000/api/auth/token/login/
Content-Type: application/json

{
    "password": "0123456789",
    "email": "admin@admin.ru"
}
###
POST http://127.0.0.1:8000/api/auth/token/login/
Content-Type: application/json

{
    "password": "Qwerty123",
    "email": "vpupkin9@yandex.ru"
}
###
GET http://127.0.0.1:8000/api/users/me/
###
GET http://127.0.0.1:8000/api/users/me/
Authorization: Token 7018a6e6ce04ae3542c95abd631e0583ff3b9f6a
###
POST http://127.0.0.1:8000/api/users/
Content-Type: application/json

{
    "email": "vpupkin10@yandex.ru",
    "username": "vasya.pupkin10",
    "first_name": "Вася10",
    "last_name": "Пупкин10",
    "password": "Qwerty123"
}
###
POST http://127.0.0.1:8000/api/users/set_password/
Content-Type: application/json
Authorization: Token 7018a6e6ce04ae3542c95abd631e0583ff3b9f6a

{
    "new_password": "0123456789",
    "current_password": "987654321"
}
###
POST http://127.0.0.1:8000/api/users/set_password/
Content-Type: application/json
Authorization: Token 7018a6e6ce04ae3542c95abd631e0583ff3b9f6a

{
    "new_password": "987654321"
}
###
POST http://127.0.0.1:8000/api/users/set_password/
Content-Type: application/json

{
    "new_password": "987654321",
    "current_password": "0123456789"
}
###
POST http://127.0.0.1:8000/api/auth/token/logout/
Content-Type: application/json
Authorization: Token 7018a6e6ce04ae3542c95abd631e0583ff3b9f6a




###
# Теги
###
GET http://127.0.0.1:8000/api/tags/
###
GET http://127.0.0.1:8000/api/tags/2/



###
# Ингридиенты
###
GET http://127.0.0.1:8000/api/ingredients/
###
GET http://127.0.0.1:8000/api/ingredients/3/
###
GET http://127.0.0.1:8000/api/ingredients/?search=абрикосовый
###



###
# Рецепты
###
GET http://127.0.0.1:8000/api/recipes/
###
GET http://127.0.0.1:8000/api/recipes/
Authorization: Token 7018a6e6ce04ae3542c95abd631e0583ff3b9f6a
###
GET http://127.0.0.1:8000/api/recipes/?limit=2
Authorization: Token 7018a6e6ce04ae3542c95abd631e0583ff3b9f6a
###
GET http://127.0.0.1:8000/api/recipes/15/
###
GET http://127.0.0.1:8000/api/recipes/?is_favorited=1
Authorization: Token 7018a6e6ce04ae3542c95abd631e0583ff3b9f6a
###
GET http://127.0.0.1:8000/api/recipes/?is_in_shopping_cart=1
Authorization: Token 7018a6e6ce04ae3542c95abd631e0583ff3b9f6a
###
GET http://127.0.0.1:8000/api/recipes/?author=Oleg
Authorization: Token 7018a6e6ce04ae3542c95abd631e0583ff3b9f6a
###
GET http://127.0.0.1:8000/api/recipes/?tags=breakfast
Authorization: Token 7018a6e6ce04ae3542c95abd631e0583ff3b9f6a
###
POST http://127.0.0.1:8000/api/recipes/
Content-Type: application/json
Authorization: Token 7018a6e6ce04ae3542c95abd631e0583ff3b9f6a

{
  "ingredients": [
    {
      "id": 1123,
      "amount": 14
    }
  ],
  "tags": [
    1,
    2
  ],
  "image": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAgMAAABieywaAAAACVBMVEUAAAD///9fX1/S0ecCAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAACklEQVQImWNoAAAAggCByxOyYQAAAABJRU5ErkJggg==",
  "name": "string",
  "text": "string",
  "cooking_time": 1
}
###
PATCH  http://127.0.0.1:8000/api/recipes/16/
Content-Type: application/json
Authorization: Token 7018a6e6ce04ae3542c95abd631e0583ff3b9f6a

{
  "ingredients": [
    {
      "id": 1123,
      "amount": 11
    }
  ],
  "tags": [
    1,
    2
  ],
  "image": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAgMAAABieywaAAAACVBMVEUAAAD///9fX1/S0ecCAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAACklEQVQImWNoAAAAggCByxOyYQAAAABJRU5ErkJggg==",
  "name": "string3",
  "text": "string3",
  "cooking_time": 1
}
###
DELETE  http://127.0.0.1:8000/api/recipes/14/
Authorization: Token 7018a6e6ce04ae3542c95abd631e0583ff3b9f6a
