version: "3.3"

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_database:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - 127.0.0.1:5432:5432
  
  backend:
    # https://hub.docker.com/repository/docker/olegtsss/foodgram/general
    image:  olegtsss/foodgram:v1.03.2023
    restart: always
    depends_on:
      - db
    env_file:
      - ./.env
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
 
  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build/:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - /etc/letsencrypt/:/etc/nginx/conf.d/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - backend

volumes:
  static_value:
  media_value:
  postgres_database:
