# Generated by Django 2.2.19 on 2023-03-15 03:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='Username валидируемого пользователя')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Адрес электронной почты')),
                ('first_name', models.CharField(max_length=150, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('password', models.CharField(max_length=150, verbose_name='Пароль')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активный')),
                ('email_hash', models.CharField(max_length=40, verbose_name='Email hash')),
                ('confirmation_code', models.CharField(blank=True, max_length=64, verbose_name='Cсылка подтверждения')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='Счетчик попыток')),
            ],
            options={
                'verbose_name': 'запись о проверке',
                'verbose_name_plural': 'Верификация email',
                'ordering': ('pk',),
            },
        ),
    ]
