# Generated by Django 2.2.19 on 2023-02-22 04:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(help_text='Укажите автора рецепта', on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.IntegerField(help_text='Введите время приготовления (в минутах)', validators=[django.core.validators.MinValueValidator(1, 'Указано не корректное время приготовления.'), django.core.validators.MaxValueValidator(10080, 'Указано не корректное время приготовления.')], verbose_name='Время приготовления'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(help_text='Выберете картинку для рецепта', upload_to='recipes/', verbose_name='Картинка'),
        ),
    ]
