# Generated by Django 2.2.19 on 2023-02-24 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('pk',), 'verbose_name': 'пользователя', 'verbose_name_plural': '1. Пользователи'},
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(help_text='Выберете картинку для рецепта', upload_to='static/', verbose_name='Картинка'),
        ),
    ]
