# Надо исправить: Лишние комментарии из урока лучше удалить
version: '3.3'

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    volumes:
      - ./frontend/:/app/result_build/
  nginx:
    image: nginx:1.19.3
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static:/var/html/static/django/
      - ./media:/var/html/media/
      - ./frontend/build:/usr/share/nginx/html

