# Generated by Django 2.2.19 on 2023-03-01 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'ordering': ('pk',), 'verbose_name': 'подписку', 'verbose_name_plural': '2. Подписки'},
        ),
    ]
